// Offline fallback data — used only if the backend API is unreachable,
// so the UI still renders. The live app loads this same data from the database.
export const CATEGORIES_FALLBACK = [
  { id: 1, name: "Burger", emoji: "🍔" },
  { id: 2, name: "Pizza", emoji: "🍕" },
  { id: 3, name: "Chicken", emoji: "🍗" },
  { id: 4, name: "Fries", emoji: "🍟" },
  { id: 5, name: "Drinks", emoji: "🥤" },
  { id: 6, name: "Dessert", emoji: "🍰" },
];

export const FOODS_FALLBACK = [
  { id: 1, name: "Classic Royale Burger", restaurant: "Burger Flame", category: "Burger", price: 9.8, emoji: "🍔", img: "https://loremflickr.com/600/600/burger?lock=10", rating: 4.8, time: "25 min", distance: "1.4 km", kcal: 198, protein: 25, fat: 13, carbs: 23, description: "A flame-grilled beef patty layered with crisp lettuce, ripe tomato, melted cheddar and our signature house sauce on a toasted brioche bun." },
  { id: 2, name: "Spicy Inferno Pizza", restaurant: "Pizza Craft", category: "Pizza", price: 12.5, emoji: "🍕", img: "https://loremflickr.com/600/600/pizza?lock=20", rating: 4.7, time: "30 min", distance: "2.1 km", kcal: 285, protein: 14, fat: 11, carbs: 34, description: "Wood-fired thin crust loaded with pepperoni, jalapenos, red chilli flakes and a fiery hot-sauce drizzle for heat lovers." },
  { id: 3, name: "Chicken Fried Rice", restaurant: "Nom Nom House", category: "Chicken", price: 8.0, emoji: "🍛", img: "https://loremflickr.com/600/600/rice?lock=30", rating: 4.6, time: "20 min", distance: "1.1 km", kcal: 240, protein: 18, fat: 9, carbs: 30, description: "Wok-tossed jasmine rice with tender chicken, egg, spring onions and a savoury soy-garlic glaze." },
  { id: 4, name: "Beef Cheesy Delight", restaurant: "Crunch Kitchen", category: "Burger", price: 11.2, emoji: "🧀", img: "https://loremflickr.com/600/600/burger?lock=40", rating: 4.9, time: "28 min", distance: "1.8 km", kcal: 310, protein: 28, fat: 16, carbs: 18, description: "Double smashed beef stacked with a molten cheese core, caramelised onions and smoked aioli." },
  { id: 5, name: "Crispy Fries", restaurant: "Burger Flame", category: "Fries", price: 4.5, emoji: "🍟", img: "https://loremflickr.com/600/600/fries?lock=50", rating: 4.5, time: "15 min", distance: "1.4 km", kcal: 312, protein: 4, fat: 15, carbs: 41, description: "Golden hand-cut fries, double-fried for maximum crunch and dusted with sea salt." },
  { id: 6, name: "Fresh Orange Juice", restaurant: "Crunch Kitchen", category: "Drinks", price: 3.8, emoji: "🧃", img: "https://loremflickr.com/600/600/juice?lock=60", rating: 4.4, time: "10 min", distance: "1.8 km", kcal: 110, protein: 2, fat: 0, carbs: 26, description: "Cold-pressed seasonal oranges, no added sugar - bright, sweet and refreshing." },
  { id: 7, name: "Garlic Butter Chicken", restaurant: "Nom Nom House", category: "Chicken", price: 10.5, emoji: "🍗", img: "https://loremflickr.com/600/600/chicken?lock=71", rating: 4.7, time: "22 min", distance: "1.1 km", kcal: 280, protein: 32, fat: 12, carbs: 15, description: "Succulent chicken thighs roasted with aromatic garlic butter and fresh herbs." },
  { id: 8, name: "Veggie Supreme Pizza", restaurant: "Pizza Craft", category: "Pizza", price: 11.0, emoji: "🍕", img: "https://loremflickr.com/600/600/pizza?lock=72", rating: 4.6, time: "28 min", distance: "2.1 km", kcal: 240, protein: 10, fat: 8, carbs: 32, description: "Fresh vegetables including bell peppers, mushrooms, olives and artichoke hearts on a crispy crust." },
  { id: 9, name: "Loaded Mac & Cheese", restaurant: "Crunch Kitchen", category: "Chicken", price: 9.2, emoji: "🧀", img: "https://loremflickr.com/600/600/pasta?lock=73", rating: 4.5, time: "20 min", distance: "1.8 km", kcal: 420, protein: 15, fat: 22, carbs: 42, description: "Creamy three-cheese sauce with tender pasta and crispy bacon bits on top." },
  { id: 10, name: "Grilled Fish Tacos", restaurant: "Burger Flame", category: "Chicken", price: 10.8, emoji: "🌮", img: "https://loremflickr.com/600/600/fish?lock=74", rating: 4.8, time: "24 min", distance: "1.4 km", kcal: 185, protein: 22, fat: 8, carbs: 18, description: "Seasoned grilled fish in warm tortillas with cabbage slaw, lime crema and cilantro." },
  { id: 11, name: "Strawberry Cheesecake", restaurant: "Sweet Bites", category: "Dessert", price: 6.5, emoji: "🍰", img: "https://loremflickr.com/600/600/cake?lock=75", rating: 4.9, time: "5 min", distance: "0.8 km", kcal: 340, protein: 6, fat: 18, carbs: 38, description: "Rich creamy cheesecake topped with fresh strawberries and a delicate graham cracker crust." },
  { id: 12, name: "Iced Vanilla Latte", restaurant: "Coffee Corner", category: "Drinks", price: 5.2, emoji: "☕", img: "https://loremflickr.com/600/600/coffee?lock=76", rating: 4.6, time: "10 min", distance: "0.6 km", kcal: 180, protein: 6, fat: 5, carbs: 22, description: "Smooth espresso shots blended with creamy cold milk and a hint of vanilla." },
  { id: 13, name: "Bacon Avocado Burger", restaurant: "Burger Flame", category: "Burger", price: 11.5, emoji: "🥑", img: "https://loremflickr.com/600/600/burger?lock=77", rating: 4.8, time: "26 min", distance: "1.4 km", kcal: 420, protein: 26, fat: 24, carbs: 25, description: "Juicy burger with crispy bacon, fresh avocado slices and chipotle mayo." },
  { id: 14, name: "Margherita Pizza", restaurant: "Pizza Craft", category: "Pizza", price: 10.0, emoji: "🍕", img: "https://loremflickr.com/600/600/pizza?lock=78", rating: 4.9, time: "25 min", distance: "2.1 km", kcal: 220, protein: 9, fat: 6, carbs: 28, description: "Classic pizza with fresh mozzarella, ripe tomato, fresh basil and olive oil." },
  { id: 15, name: "Teriyaki Chicken Bowl", restaurant: "Nom Nom House", category: "Chicken", price: 9.5, emoji: "🍱", img: "https://loremflickr.com/600/600/rice?lock=79", rating: 4.7, time: "19 min", distance: "1.1 km", kcal: 265, protein: 24, fat: 7, carbs: 28, description: "Glazed chicken with steamed rice, broccoli and sesame seeds in a savory teriyaki sauce." },
  { id: 16, name: "Sweet Potato Fries", restaurant: "Crunch Kitchen", category: "Fries", price: 5.5, emoji: "🍠", img: "https://loremflickr.com/600/600/fries?lock=80", rating: 4.7, time: "18 min", distance: "1.8 km", kcal: 280, protein: 3, fat: 12, carbs: 38, description: "Crispy golden sweet potato fries dusted with sea salt and a hint of cinnamon." },
  { id: 17, name: "Mango Smoothie", restaurant: "Coffee Corner", category: "Drinks", price: 4.8, emoji: "🥭", img: "https://loremflickr.com/600/600/smoothie?lock=81", rating: 4.5, time: "12 min", distance: "0.6 km", kcal: 140, protein: 2, fat: 0, carbs: 32, description: "Refreshing blend of ripe mangoes with yogurt and a touch of honey." },
  { id: 18, name: "Triple Stack Burger", restaurant: "Burger Flame", category: "Burger", price: 13.8, emoji: "🍔", img: "https://loremflickr.com/600/600/burger?lock=82", rating: 4.9, time: "30 min", distance: "1.4 km", kcal: 580, protein: 45, fat: 32, carbs: 28, description: "Three succulent beef patties stacked with triple cheese, bacon and caramelized onions." },
  { id: 19, name: "Chocolate Brownie", restaurant: "Sweet Bites", category: "Dessert", price: 4.2, emoji: "🍫", img: "https://loremflickr.com/600/600/chocolate?lock=83", rating: 4.8, time: "5 min", distance: "0.8 km", kcal: 380, protein: 4, fat: 20, carbs: 45, description: "Fudgy warm chocolate brownie served with a scoop of vanilla ice cream." },
];

export const HERO_SLIDES = [
  { badge: "30% OFF", title: "Special Offer", caption: "Get 30% off all burgers this week", emoji: "🍔", img: "https://purepng.com/public/uploads/large/purepng.com-hamburgerhamburgerburgerhamburger-fastfood-1415227432870bx1pl.png", cta: "Order Now", action: "order" },
  { badge: "FREE", title: "Free Delivery", caption: "On your first 3 orders, no minimum", emoji: "🍕", img: "https://purepng.com/public/uploads/large/purepng.com-pizzapizzaitalian-dishpie-1415227409768dmhzx.png", cta: "Grab Deal", action: "order" },
  { badge: "NEW", title: "Sweet Tooth?", caption: "Fresh desserts starting at just $3.50", emoji: "🍰", img: "https://purepng.com/public/uploads/large/purepng.com-cakecakecake-with-berries-1415228219283ybvdy.png", cta: "Explore", action: "explore" },
  { badge: "HEALTHY", title: "Fresh & Cold", caption: "Cold-pressed juices made daily", emoji: "🥤", img: "https://purepng.com/public/uploads/large/purepng.com-juiceorange-juicejuice-1415228256309zc6h7.png", cta: "Order Now", action: "order" },
];

export const RESTAURANTS = [
  { id: 1, name: "Burger Flame", cuisine: "American, Burgers", rating: 4.8, reviews: 245, distance: 1.4, time: "25 min", location: "Downtown", lat: 40.7128, lng: -74.0060, image: "🍔", testimonials: [{ name: "John D.", text: "Best burgers in town! Fresh and delicious." }, { name: "Sarah M.", text: "Amazing service and great quality." }] },
  { id: 2, name: "Pizza Craft", cuisine: "Italian, Pizza", rating: 4.7, reviews: 189, distance: 2.1, time: "30 min", location: "Midtown", lat: 40.7580, lng: -73.9855, image: "🍕", testimonials: [{ name: "Mike P.", text: "Authentic pizza with quality ingredients." }, { name: "Emma L.", text: "Perfect for family gatherings!" }] },
  { id: 3, name: "Nom Nom House", cuisine: "Asian, Chinese", rating: 4.6, reviews: 312, distance: 1.1, time: "20 min", location: "East Side", lat: 40.7489, lng: -73.9680, image: "🍛", testimonials: [{ name: "Lisa K.", text: "Fresh ingredients and authentic flavors." }, { name: "David C.", text: "Never disappoints, highly recommended." }] },
  { id: 4, name: "Crunch Kitchen", cuisine: "Fast Food, Sides", rating: 4.5, reviews: 156, distance: 1.8, time: "18 min", location: "West Plaza", lat: 40.7505, lng: -74.0060, image: "🍟", testimonials: [{ name: "Alex T.", text: "Quick service, crispy and fresh." }, { name: "Rachel G.", text: "Great value for money!" }] },
  { id: 5, name: "Coffee Corner", cuisine: "Cafe, Beverages", rating: 4.4, reviews: 278, distance: 0.6, time: "10 min", location: "City Center", lat: 40.7614, lng: -73.9776, image: "☕", testimonials: [{ name: "Tom H.", text: "Best coffee around! Amazing atmosphere." }, { name: "Nina S.", text: "Perfect for morning meetings." }] },
  { id: 6, name: "Sweet Bites", cuisine: "Desserts, Bakery", rating: 4.9, reviews: 298, distance: 0.8, time: "5 min", location: "Arts District", lat: 40.7505, lng: -74.0000, image: "🍰", testimonials: [{ name: "Jennifer W.", text: "Heavenly desserts! Try their cheesecake." }, { name: "Chris B.", text: "Worth every visit. Pure delight!" }] },
];
